modLoader="javafml"
loaderVersion="[47,)"
license="BSD-3-Clause"

[[mods]]
modId="sign_up"
version="${file.jarVersion}"
displayName="Sign Me Up"
authors="TeaConMC, 3TUSK, yuesha-yc (YueSha), Hookan, ustc-zzzz"
description="Sign up, sign in, in-game guide map and more."

[[dependencies.sign_up]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.sign_up]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
